service:  "shoppingcart"
consumer:  "uniqlo"
interactions:  {
  request:  {
    [type.googleapis.com/shoppingcart.AddItemRequest]:  {
      item_id:  1
    }
  }
  response:  {
    [type.googleapis.com/shoppingcart.AddItemResponse]:  {
      added:  true
    }
  }
}
