// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package contract

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ContractServiceClient is the client API for ContractService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContractServiceClient interface {
	// Publish a contract for the consumer to the repository.
	PublishContract(ctx context.Context, in *PublishContractRequest, opts ...grpc.CallOption) (*PublishContractResponse, error)
	// Runs the provider verfication tests.
	VerificationTest(ctx context.Context, in *VerificationTestRequest, opts ...grpc.CallOption) (*VerificationTestResponse, error)
}

type contractServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContractServiceClient(cc grpc.ClientConnInterface) ContractServiceClient {
	return &contractServiceClient{cc}
}

func (c *contractServiceClient) PublishContract(ctx context.Context, in *PublishContractRequest, opts ...grpc.CallOption) (*PublishContractResponse, error) {
	out := new(PublishContractResponse)
	err := c.cc.Invoke(ctx, "/contract.ContractService/PublishContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractServiceClient) VerificationTest(ctx context.Context, in *VerificationTestRequest, opts ...grpc.CallOption) (*VerificationTestResponse, error) {
	out := new(VerificationTestResponse)
	err := c.cc.Invoke(ctx, "/contract.ContractService/VerificationTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContractServiceServer is the server API for ContractService service.
// All implementations must embed UnimplementedContractServiceServer
// for forward compatibility
type ContractServiceServer interface {
	// Publish a contract for the consumer to the repository.
	PublishContract(context.Context, *PublishContractRequest) (*PublishContractResponse, error)
	// Runs the provider verfication tests.
	VerificationTest(context.Context, *VerificationTestRequest) (*VerificationTestResponse, error)
	mustEmbedUnimplementedContractServiceServer()
}

// UnimplementedContractServiceServer must be embedded to have forward compatible implementations.
type UnimplementedContractServiceServer struct {
}

func (UnimplementedContractServiceServer) PublishContract(context.Context, *PublishContractRequest) (*PublishContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishContract not implemented")
}
func (UnimplementedContractServiceServer) VerificationTest(context.Context, *VerificationTestRequest) (*VerificationTestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerificationTest not implemented")
}
func (UnimplementedContractServiceServer) mustEmbedUnimplementedContractServiceServer() {}

// UnsafeContractServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContractServiceServer will
// result in compilation errors.
type UnsafeContractServiceServer interface {
	mustEmbedUnimplementedContractServiceServer()
}

func RegisterContractServiceServer(s grpc.ServiceRegistrar, srv ContractServiceServer) {
	s.RegisterService(&ContractService_ServiceDesc, srv)
}

func _ContractService_PublishContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).PublishContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contract.ContractService/PublishContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).PublishContract(ctx, req.(*PublishContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractService_VerificationTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerificationTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).VerificationTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contract.ContractService/VerificationTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).VerificationTest(ctx, req.(*VerificationTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContractService_ServiceDesc is the grpc.ServiceDesc for ContractService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContractService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contract.ContractService",
	HandlerType: (*ContractServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishContract",
			Handler:    _ContractService_PublishContract_Handler,
		},
		{
			MethodName: "VerificationTest",
			Handler:    _ContractService_VerificationTest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contract/contract.proto",
}
