service:  "shoppingcart"
consumer:  "fooshop"
interactions:  {
  name:  "Add item to cart"
  method:  "AddItem"
  request:  {
    [type.googleapis.com/shoppingcart.AddItemRequest]:  {
      item_id:  1
    }
  }
  response:  {
    [type.googleapis.com/shoppingcart.AddItemResponse]:  {
      added:  true
    }
  }
}
